# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Mad Mod Labs 68"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Mad Mod Labs"
chip = "rp2040"
product_name = "68-Key Mechanical Keyboard"

[matrix]
rows = 5
cols = 15
io_type = "col2row"
matrix_type = "normal"

input_pins = ["GP0", "GP1", "GP2", "GP3", "GP4"]
output_pins = [
    "GP5", "GP6", "GP7", "GP8", "GP9",
    "GP10", "GP11", "GP12", "GP13", "GP14",
    "GP15", "GP16", "GP17", "GP18", "GP19"
]

[layout]
rows = 5
cols = 15
layers = 2

[layout.keymap]
layer_0 = [
    # Row 0: ESC, 1-0, -, =, Backspace, `
    ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus", "Equal", "Bspace", "Grave"],
    
    # Row 1: Tab, Q-P, [, ], \, Page Up
    ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LBracket", "RBracket", "Bslash", "PgUp"],
    
    # Row 2: Caps Lock, A-;, ', Enter, Page Down
    ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "Enter", "PgDown"],
    
    # Row 3: Left Shift, Z-/, Right Shift, Up, Delete
    ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "RShift", "Up", "Delete"],
    
    # Row 4: Ctrl, GUI, Alt, Space, Alt, Fn, Ctrl, Left, Down, Right
    ["LCtrl", "LGui", "LAlt", "Space", "RAlt", "Mo(1)", "RCtrl", "Left", "Down", "Right"]
]

# Function layer (activated by Fn key - Mo(1))
layer_1 = [
    # Row 0: Function keys
    ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "Delete", "__"],
    
    # Row 1: Media controls
    ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "Home"],
    
    # Row 2
    ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "End"],
    
    # Row 3: Volume and brightness
    ["__", "__", "__", "__", "__", "__", "__", "__", "VolDown", "VolUp", "Mute", "__", "BriUp", "__"],
    
    # Row 4
    ["__", "__", "__", "__", "__", "__", "__", "MediaPrev", "BriDown", "MediaNext"]
]
