# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "rp2040"
product_name = "68-Key Mechanical Keyboard"

[matrix]
rows = 5
cols = 15
# COL2ROW means diodes point from columns to rows
io_type = "col2row"
matrix_type = "normal"

# Teensy 2.0 to RP2040 Pin Mapping
# Original Teensy pins → RP2040 GPIO pins
# Row Pins: B0, B1, B2, B3, B4 → GP0-GP4
# Col Pins: B5, B6, B7, C0-C7, D0-D3 → GP5-GP19
input_pins = ["GP0", "GP1", "GP2", "GP3", "GP4"]
output_pins = [
    "GP5", "GP6", "GP7", "GP8", "GP9",
    "GP10", "GP11", "GP12", "GP13", "GP14",
    "GP15", "GP16", "GP17", "GP18", "GP19"
]

[layout]
rows = 5
cols = 15
layers = 1

# Keymap directly from your QMK configuration
[layout.keymap]
layer_0 = [
    # Row 0: ESC, 1-0, -, =, Backspace, `
    ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus", "Equal", "Bspace", "Grave"],
    
    # Row 1: Tab, Q-P, [, ], \, Page Up
    ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LBracket", "RBracket", "Bslash", "PgUp"],
    
    # Row 2: Caps Lock, A-;, ', Enter, Page Down
    ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "Enter", "PgDown", "No"],
    
    # Row 3: Left Shift, Z-/, Right Shift, (empty), Delete
    ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "LShift", "No", "Delete", "No"],
    
    # Row 4: Ctrl, GUI, Alt, Space, Alt, (empty), Ctrl, (empty x3)
    ["LCtrl", "LGui", "LAlt", "Space", "LAlt", "No", "LCtrl", "No", "No", "No", "No", "No", "No", "No", "No"]
]
