# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Mad Mod Labs 68"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Mad Mod Labs"
chip = "rp2040"

[matrix]
rows = 5
cols = 15
io_type = "col2row"
matrix_type = "normal"

input_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3", "PIN_4"]
output_pins = [
    "PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9",
    "PIN_10", "PIN_11", "PIN_12", "PIN_13", "PIN_14",
    "PIN_15", "PIN_16", "PIN_17", "PIN_18", "PIN_19"
]

[layout]
rows = 5
cols = 15
layers = 2

# Keymap as a 3D array: [layers][rows][cols]
keymap = [
    # Layer 0 - Base layer
    [
        # Row 0
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus", "Equal", "Backspace", "Grave"],
        # Row 1
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LeftBracket", "RightBracket", "Backslash", "PageUp"],
        # Row 2
        ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "Enter", "PageDown", "__"],
        # Row 3
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "RShift", "Up", "Delete", "__"],
        # Row 4
        ["LCtrl", "LGui", "LAlt", "Space", "RAlt", "RGui", "RCtrl", "Left", "Down", "Right", "__", "__", "__", "__", "__"]
    ],
    ]
    # Layer 1 - Function layer
#     [
#         # Row 0
#         ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "Delete", "__"],
#         # Row 1
#         ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "Home"],
#         # Row 2
#         ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "End", "__"],
#         # Row 3
#         ["__", "__", "__", "__", "__", "__", "__", "__", "VolumeDown", "VolumeUp", "Mute", "__", "BriUp", "__", "__"],
#         # Row 4
#         ["__", "__", "__", "__", "__", "__", "__", "MediaPrev", "BriDown", "MediaNext", "__", "__", "__", "__", "__"]
#     ]
# ]
